[package]
name = "rusty_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty_config = { path = "../rusty_config" }

thiserror = "2.0.17"
tracing = { version = "=0.1.44"}
tracing-subscriber = { version = "=0.3.22", features = ["env-filter"]}