[package]
name = "rusty_server"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty_http = { path = "../rusty_http" }
rusty_router = { path = "../rusty_router" }
rusty_utils = { path = "../rusty_utils" }

thiserror = "2.0.17"
tracing = { version = "=0.1.44"}