[package]
name = "forge-logging"
version = "0.1.0"
edition = "2024"

[dependencies]
forge-config = { path = "../forge-config" }

tracing = { version = "=0.1.44"}
tracing-subscriber = { version = "=0.3.22", features = ["env-filter"]}
