[package]
name = "forge-http"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
tracing = { version = "=0.1.44"}
tokio = { version = "1.49.0", features = ["net", "io-util"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"